### ISSUE TITLE
Swift Bridging-Header import error help.

### ISSUE THREAD

**Issue by kimjiwook** [IFTTT/JazzHands#1065]
pod install (Next)
Swift Project Bridging-Hearder.h
import JazzHands.. Buil Error help me..

JazzHandsDemo (The run is well)

![2014-12-05 5 12 09](https://cloud.githubusercontent.com/assets/4971814/5312721/034df0e6-7ca2-11e4-9654-0fe94f820d87.png)
![2014-12-05 5 12 26](https://cloud.githubusercontent.com/assets/4971814/5312722/035023ac-7ca2-11e4-8c59-5d8b6e9291d8.png)

**Comment by sealband** [comment]
i find that in IFTTTAnimationFrame.h @import UIKit didn't add

**Comment by DianaLeo** [comment]
When I installed JazzHands to swift 1.2 project, there was an issue: cannot find interface declaration for 'nsobject' superclass of IFTTTAnimator. After adding "#import <UIKit/UIKit.h>" in IFTTTAnimator.h, the problem is solved.
