### ISSUE TITLE
Transform square into circle

### ISSUE THREAD

**Issue by nunogoncalves** [IFTTT/JazzHands#1495]
Ok, i realize this is not an issue and I'm sorry for that. 
But I was wondering if it is possible to transform a square into a circle and vice versa and if so, how could I accomplish that? 

Thanks in advance.

**Comment by jhersh** [comment]
You could make a simple subclass of `IFTTTAnimation` that animates the `layer.cornerRadius` property. Have a look at `IFTTTAlphaAnimation` for something similar.

**Comment by nunogoncalves** [comment]
Thank you @jhersh. :)

I managed to do it. 

Would you be interested in accepting a PR with that feature if I managed to create it successfully? I say if I managed because I'm still very green with iOS dev, one month exp, and only in swift.

**Comment by jhersh** [comment]
Sure!
