### ISSUE TITLE
No Corner Radius Animation in Pod?

### ISSUE THREAD

**Issue by nickbewley** [IFTTT/JazzHands#1526]
Hey there! 

Curious if there is a reason why IFTTTCornerRadiusAnimation is not available in the pod? 

Am I missing something there? 

Thanks a ton!
Nick

**Comment by jhersh** [comment]
It was in `master` but not yet part of a release. I have just released JazzHands [`0.2.1`](https://github.com/IFTTT/JazzHands/releases/tag/0.2.1).

In the future, you can point any pod to the bleeding-edge in your Podfile, with all the risk (and reward!) that entails:

```
pod 'JazzHands', :head
```

**Comment by nickbewley** [comment]
Awesome thanks
