### ISSUE TITLE
How to use it in AutoLayout ?

### ISSUE THREAD

**Issue by nsdictionary** [IFTTT/JazzHands#1663]
hello,

you say we use this framework , we should turn off autolayout first,

but,now,we must use auto layout,can you show me how to use this framework for auto layout? 

thank U

**Comment by jhersh** [comment]
JazzHands definitely doesn't require you to turn off AutoLayout. You can animate the constant of an AutoLayout constraint with [IFTTTConstraintsAnimation](https://github.com/IFTTT/JazzHands/blob/master/JazzHands/IFTTTConstraintsAnimation.m).

**Comment by lauraskelton** [comment]
@nsdictionary JazzHands 2.0 now includes a demo that shows how to use easily use AutoLayout in your animated paging scroll view.
