### ISSUE TITLE
Is it possible to animate when page scroll stops?

### ISSUE THREAD

**Issue by chiahsien** [IFTTT/JazzHands#1674]
I understand that Jazzhands's concept is keyframe, so the animations happen during page scrolling.

I'd like to know if it's possible to do some animations when scroll stops?
For example: after (not during) I scroll from page 1 to page 2, I can zoom in/out a button in page 2.

If it's possible, what is the best practice to do it?

**Comment by lauraskelton** [comment]
Hi @chiahsien, You probably wouldn't use JazzHands to perform this type of animation, but it can work nicely alongside JazzHands.

You could set your view controller as the scroll view's delegate, respond to `scrollViewDidEndScrollingAnimation:`, `scrollViewDidEndDecelerating:`, and `scrollViewDidEndDragging:willDecelerate:` (that last one only if `willDecelerate` is false), and check what page you're on to decide if you want to begin playing animations using something like `[UIView animateWithDuration:`.
