### ISSUE TITLE
Handle Gestures

### ISSUE THREAD

**Issue by confile** [IFTTT/JazzHands#1675]
In your pan example you wrote: 

```
- (IBAction)handlePan:(UIPanGestureRecognizer *)recognizer {
  [self.animator animate:[recognizer locationOfTouch:0 inView:self.view]];
}
```
This is wrong because ``locationOfTouch``will return a ``CGPoint`` is there a way to fix that?

**Comment by confile** [comment]
Could you please explain how I can use JazzHands with a pan gesture?

**Comment by jhersh** [comment]
For a horizontal pan, you could look at just the `x` component of that point.

**Comment by confile** [comment]
Do you have an example for that, because it seems that I have to adjust the value of x somehow. 

Is it possible to make a second animation on a vertical pan gesture beside the horizontal animation from the scrollView?

**Comment by jhersh** [comment]
The value of `x` in that example will change over time as the user moves the pan gesture around. You can certainly use the `y` coordinate to power a second animator with its own animations.

**Comment by confile** [comment]
Could you please post an example or extend you example. That would help a lot.

**Comment by jhersh** [comment]
You're right there is a small typo in the example. Here is one way to fix it:

```
- (IBAction)handlePan:(UIPanGestureRecognizer *)recognizer {
  [self.animator animate:[recognizer locationOfTouch:0 inView:self.view].x];
}
```

**Comment by lauraskelton** [comment]
@confile This is updated in the new README.
