### ISSUE TITLE
Swift DSL for JazzHands

### ISSUE THREAD

**Issue by confile** [IFTTT/JazzHands#1677]
Hi,

I created a Swift DSL for JazzHands. You can find it here: 

https://github.com/confile/JazzHandsSwift

It would be great if you could linke to this DSL if you like it.

**Comment by confile** [comment]
@lauraskelton I updated my lib for JazzHands 2.0.0

**Comment by dmyers** [comment]
:+1: I was wanting to use Swift too.

**Comment by lauraskelton** [comment]
@confile @dmyers We've secretly been working on a Swift version of JazzHands for some time now, and just made it public today! Check out [RazzleDazzle](https://github.com/IFTTT/RazzleDazzle), the Carthage-compatible, fully Swift version of JazzHands, and let us know what you think!

**Comment by dmyers** [comment]
@lauraskelton Sweet! Thanks for sharing.

**Comment by confile** [comment]
Looks nice, but I think that my DSL is much simpler to use.
