### ISSUE TITLE
SnapKit integration

### ISSUE THREAD

**Issue by confile** [IFTTT/JazzHands#1681]
Would it be possible to use [SnapKit](https://github.com/SnapKit/SnapKit) AutoLayout with JazzHands Animation somehow?

**Comment by lauraskelton** [comment]
@confile Sure! You'd have to write a custom animation (see `MyCustomAnimation` in the Demo app for an easy example), but all you'd have to do is to animate the constant values of one of your SnapKit constraints in your animation.

For example,

```objc
// make some constraints
view1.snp_makeConstraints { (make) -> Void in
  self.topConstraint = make.top.equalTo(superview).offset(padding.top).constraint
  make.left.equalTo(superview).offset(padding.left)
}

// add some animation keyframes for what the offset should be at different times

// Then, inside of your custom animation's `animate:` method, just use the value at the given time to animate the constraint's offset.
self.topConstraint.updateOffset(VALUE_FOR_THIS_TIME)
```

**Comment by lauraskelton** [comment]
If you want to use the super easy `keepView:onPage:` methods in `IFTTTAnimatedPagingScrollViewController` along with your SnapKit auto layout constraints, just add your SnapKit constraints as you normally would but make sure not to add any constraint that would set the view's x-position (like Center X, Left, or Right).

Then, you should be able to safely use `keepView:onPage` without conflicting with SnapKit's constraints.

**Comment by confile** [comment]
@lauraskelton Thanks for help. Using auto layout I need to set left and right otherwise I cannot position the view correctly. Is there another way to use auto layout with: ``keepView:onPage:``?
