### ISSUE TITLE
Help to put a UIImageView to the right or to the left

### ISSUE THREAD

**Issue by javiergonzper** [IFTTT/JazzHands#1684]
Hello,

I do not see the way to make the animation that you have on your gif on the page 4 and 5. First at all I can not put the UIImageView where I want to on the next page move it.

I can put it where I want on Y axis but not on the X axis. On your Unicorn example you have everything centered on the X axis but not moved to the right or the left.
Could you help me?

Thanks in advance

**Comment by javiergonzper** [comment]
@lauraskelton reading the code looks like using the - (void)keepView:(UIView *)view methods the UIView that we added can only be centered on the X axis

Are there other way to add the UIImageView to more than one page and not center on X?

**Comment by lauraskelton** [comment]
@javiergonzper I'm putting together a few more tools along with a new demo that will allow you to set the horizontal position to the left or right. It should be ready to go next week!

**Comment by javiergonzper** [comment]
Awesome @lauraskelton thank you very much! :beers:

**Comment by MattKiazyk** [comment]
+1 would love to see this as well! looking to set an image to the upper right

**Comment by lauraskelton** [comment]
@javiergonzper @MattKiazyk Check out the new methods in `IFTTTAnimatedPagingScrollViewController` - `keepView:onPage:withAttribute:`, keepView:onPages:withAttribute:`, and `keepView:onPages:atTimes:withAttribute:`. You can set the attribute to center (default), left, or right, and it will automatically match eg. the left side of the view to the left side of the pages you specify.

**Comment by javiergonzper** [comment]
Awesome @lauraskelton thank you very much for your help :wink:
