### ISSUE TITLE
Hide Animation performs differently on 32 bit and 64 bit devices

### ISSUE THREAD

**Issue by ashavit** [IFTTT/JazzHands#1692]
@lauraskelton @devinfoley Hi,
I've discovered today that the hide animation performs differently on 64 bit devices than on 32 bit.
It seems that on 64 bit devices the interpolation of hide animation returned a fraction value that was translated to true if it was nonzero, but on 32 bit it was always 0 or 1, never a fraction.
I found that @encode(BOOL) and @encode(char) returned same on 32 bit but not on 64, and NSCFBoolean has a char type.
Please see my pull request. I hope it sticks to the original idea of the method.
Thanx,
Amir.

**Comment by lauraskelton** [comment]
Great find, thanks!
